const CONDUCTOR_URI =  process.env.NEXT_PUBLIC_CONDUCTOR_URI
const ADMIN_CONDUCTOR_URI = process.env.NEXT_PUBLIC_ADMIN_CONDUCTOR_URI
const HOLO_APP_ID = process.env.NEXT_PUBLIC_HOLO_APP_ID

export {CONDUCTOR_URI, ADMIN_CONDUCTOR_URI, HOLO_APP_ID}