connectionUrl: unix://databases/keystore/socket?k=RrgYLVssvxrUsQ0qOeZANdd3jgAnfZlRhTt2UJ7ZJEU

# The pid file for managing a running lair-keystore process
pidFile: databases/keystore/pid_file

# The sqlcipher store file for persisting secrets
storeFile: databases/keystore/store_file

# Configuration for managing sign_by_pub_key fallback
# in case the pub key does not exist in the lair store.
# - `signatureFallback: none`
# - ```
#   signatureFallback: !command
#     # 'program' will resolve to a path, specifying 'echo'
#     # will try to run './echo', probably not what you want.
#     program: "./my-executable"
#     # args are optional
#     args:
#       - test-arg1
#       - test-arg2
#   ```
signatureFallback: none

# -- cryptographic secrets --
# If you modify the data below, you risk loosing access to your keys.
runtimeSecretsSalt: d7gonPaiCERLo0qvtCWksA
runtimeSecretsMemLimit: 268435456
runtimeSecretsOpsLimit: 3
runtimeSecretsContextKey:
- mNH7xC1I3ZXIJCWr3Bk3lWJdheAqr8GS
- A0VXNjxNmYdPzdOEBx34jwKPadG-TkyqFOQI5gJn432GCie-y9ocWdnIWRHwvfR4QQ
runtimeSecretsIdSeed:
- JWiKK59-hb3MuW_FsfRTFSQWkO6XHaiZ
- tqV_dVwPFMDN3TCKO5bAn8yOZJRYhQFOZPqdn3J_yqabHU6CbdVYlVoCkqUlgxhX1g
